/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 03-May-2019 17:36:47
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
     0.2301858175408,  0.02211581651039,  0.02289875642619,  0.02343142487285,
    0.02355195032281,  0.02377981060472,  0.02355195032281,  0.02343142487285,
    0.02289875642619,  0.02211581651039,   0.2301858175408
};
